"""Add ARC Intelligence Engine Phase 1 models

Revision ID: 14b2e19755ff
Revises: 0717b1245faa
Create Date: 2026-08-01 23:02:22.372755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b2e19755ff'
down_revision: Union[str, Sequence[str], None] = '0717b1245faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arc_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('observation_type', sa.String(), nullable=False),
    sa.Column('source_module', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_obj', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arc_observations_user_id'), 'arc_observations', ['user_id'], unique=False)
    op.create_table('arc_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_reasoning', sa.String(), nullable=True),
    sa.Column('ai_observation', sa.String(), nullable=True),
    sa.Column('suggested_next_action', sa.String(), nullable=True),
    sa.Column('last_evaluation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arc_profiles_user_id'), 'arc_profiles', ['user_id'], unique=True)
    op.create_table('arc_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('previous_stage', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('transition_reason', sa.String(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arc_stage_history_user_id'), 'arc_stage_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arc_stage_history_user_id'), table_name='arc_stage_history')
    op.drop_table('arc_stage_history')
    op.drop_index(op.f('ix_arc_profiles_user_id'), table_name='arc_profiles')
    op.drop_table('arc_profiles')
    op.drop_index(op.f('ix_arc_observations_user_id'), table_name='arc_observations')
    op.drop_table('arc_observations')
    # ### end Alembic commands ###
