"""Initial Schema

Revision ID: 427adddd69d7
Revises: 
Create Date: 2026-08-01 12:57:56.445503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '427adddd69d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('identity_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('aspirations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('available_time', sa.String(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_content_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('long_term_goal', sa.String(), nullable=True),
    sa.Column('identity_summary', sa.String(), nullable=True),
    sa.Column('core_motivations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_learning_approach', sa.String(), nullable=True),
    sa.Column('growth_focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
