"""add_source_to_knowledge_sources

Revision ID: a9a67bfeb9bf
Revises: 7cca2031a062
Create Date: 2026-08-01 21:39:39.927233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9a67bfeb9bf'
down_revision: Union[str, Sequence[str], None] = '7cca2031a062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_categories_name'), 'knowledge_categories', ['name'], unique=True)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_tags_name'), 'knowledge_tags', ['name'], unique=True)
    op.create_table('knowledge_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=False),
    sa.Column('key_takeaways', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_knowledge_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('curated_recommendations')
    op.drop_table('knowledge_collections')
    op.add_column('knowledge_sources', sa.Column('source', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('knowledge_sources', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.drop_column('knowledge_sources', 'provider')
    op.drop_column('knowledge_sources', 'metadata')
    op.drop_column('knowledge_sources', 'estimated_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_sources', sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_sources', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_sources', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('knowledge_sources', 'estimated_time')
    op.drop_column('knowledge_sources', 'stage')
    op.drop_column('knowledge_sources', 'domain')
    op.drop_column('knowledge_sources', 'source')
    op.create_table('knowledge_collections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_collections_pkey'))
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('curated_recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommendation_reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recommendation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], name=op.f('curated_recommendations_knowledge_source_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('curated_recommendations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('curated_recommendations_pkey'))
    )
    op.drop_table('user_knowledge_progress')
    op.drop_table('knowledge_summaries')
    op.drop_table('knowledge_history')
    op.drop_table('knowledge_bookmarks')
    op.drop_index(op.f('ix_knowledge_tags_name'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index(op.f('ix_knowledge_categories_name'), table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    # ### end Alembic commands ###
