"""Make activity_logs recommendation_id nullable for freeform reflections

Revision ID: b40f0d12a3a9
Revises: 4cf8fcd8d9bf
Create Date: 2026-08-02 04:12:43.230412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b40f0d12a3a9'
down_revision: Union[str, Sequence[str], None] = '4cf8fcd8d9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'recommendation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'recommendation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
