"""Add arc models

Revision ID: fb14352050d8
Revises: 588c9de92796
Create Date: 2026-08-01 21:57:38.967567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb14352050d8'
down_revision: Union[str, Sequence[str], None] = '588c9de92796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('START_RESOURCE', 'COMPLETE_RESOURCE', 'SKIP_RESOURCE', 'BOOKMARK', 'SUBMIT_REFLECTION', 'LIKE', 'NOT_FOR_ME', 'ALREADY_KNEW', name='activityaction'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('reflection', sa.String(), nullable=True),
    sa.Column('reflection_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress_added', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('stage_transition_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=False),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transition_history_user_id'), 'stage_transition_history', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('stage_progress', sa.Float(), nullable=False),
    sa.Column('arc_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('arc_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('stage_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_completed', sa.Integer(), nullable=False),
    sa.Column('total_reflections', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_table('recommendations')
    op.add_column('recommendation_history', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('recommendation_history', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('recommendation_history', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('recommendation_history', 'reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendation_history', 'reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('recommendation_history', 'url')
    op.drop_column('recommendation_history', 'domain')
    op.drop_column('recommendation_history', 'stage')
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('match_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recommendations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )

    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_stage_transition_history_user_id'), table_name='stage_transition_history')
    op.drop_table('stage_transition_history')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
